apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: portfolio

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - ingress.yaml

commonLabels:
  app: portfolio
  managed-by: kustomize

images:
  - name: portfolio
    newName: shrinidhiupadhyaya/portfolio:latest
    newTag: latest

configMapGenerator:
  - name: portfolio-config
    literals:
      - NGINX_PORT=6969
      - APP_NAME=DevOps Portfolio
      - ENVIRONMENT=production

replicas:
  - name: portfolio-deployment
    count: 2
